[programs.devnet]
transaction_mod = "6GP4RexVz8tdtyUTvVs4wztXmU75rXxFLpsnApWt5kJj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
url = "https://api.devnet.solana.com"
wallet = "/home/vwisor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
